language: php

php:
 - 5.5

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --no-interaction

script:
 - phpunit

after_script:
 - php vendor/bin/coveralls -v
